version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes_local

    ports:
    - "8000:8000"

    environment:
      - DEBUG=True

    volumes:
    - ./src/:/home/web/src

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

    env_file:
      - .env.dev

  db:
    image: postgres:12.0-alpine
    container_name: notes_local_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data:
